import glob
import os
import re
import shutil
import subprocess
import warnings


def _latexml_env():
    """Environment for the LaTeXML subprocesses.

    LaTeXML rasterizes graphics (TikZ/pstricks/picture and EPS/PDF figures)
    through the Perl Image::Magick module. Where that module isn't on Perl's
    default @INC -- e.g. a Homebrew LaTeXML on macOS, where it was built into a
    local ~/perl5 because the system Perl dir isn't writable -- we inject it
    via PERL5OPT. (LaTeXML's Homebrew wrapper resets PERL5LIB but leaves
    PERL5OPT alone, so this is the path that survives.) On Linux/production,
    where Image::Magick is installed into the system Perl, the glob matches
    nothing and this is a no-op.
    """
    env = os.environ.copy()
    hits = glob.glob(os.path.expanduser("~/perl5/lib/perl5/*/Image/Magick.pm"))
    if hits:
        archdir = os.path.dirname(os.path.dirname(hits[0]))
        env["PERL5OPT"] = ("-I" + archdir + " " + env.get("PERL5OPT", "")).strip()
    return env


# A lone <svg>...</svg> assumed not to nest another <svg> -- true for the
# inline graphics LaTeXML emits (one picture/tikz -> one self-contained svg).
_SVG_RE = re.compile(r"<svg\b.*?</svg>", re.DOTALL | re.IGNORECASE)
# LaTeXML's page footer ("Generated ... by LaTeXML" + a base64 mascot PNG):
# pure boilerplate that would otherwise leak into the Markdown.
_FOOTER_RE = re.compile(r"<footer\b.*?</footer>", re.DOTALL | re.IGNORECASE)
_MD_IMG_RE = re.compile(r"!\[(?P<caption>[^\]]*)\]\((?P<path>[^)\s]+)")
_HEADER_RE = re.compile(r"^(#{1,6})\s+(.*\S)\s*$")
# A line that is nothing but a structural wrapper tag pandoc couldn't drop
# (the top-level <article>/<section>/<header>/<nav> open/close tags).
_WRAPPER_TAG_RE = re.compile(
    r"^\s*</?(?:article|section|header|footer|nav)\b[^>]*>\s*$",
    re.IGNORECASE)


def _clean_html(html_path, image_dir, base):
    """Tidy LaTeXML's HTML in place before pandoc, returning #svgs extracted.

    Two things, both aimed at keeping the eventual Markdown clean:

    * Drop the page footer ("Generated by LaTeXML" + an embedded base64
      mascot image) -- boilerplate that pandoc would otherwise turn into a
      junk ``![Mascot Sammy](data:image/png;base64,...)`` reference.
    * Move any inline ``<svg>`` graphic out into its own ``.svg`` file and
      replace it with an ``<img>``. latexmlpost rasterizes most figures to
      PNG, but simple picture/TikZ graphics can come through as inline svg;
      turning every figure into a file reference is what lets pandoc drop raw
      HTML entirely (``-raw_html``) without losing any graphics.
    """
    with open(html_path, encoding="utf-8") as f:
        html = f.read()

    html = _FOOTER_RE.sub("", html)

    count = [0]

    def repl(match):
        svg = match.group(0)
        count[0] += 1
        name = f"{base}-inline-{count[0]}.svg"
        # A bare LaTeXML <svg> may lack the xmlns it needs to stand alone.
        if "xmlns" not in svg.split(">", 1)[0]:
            svg = svg.replace(
                "<svg", '<svg xmlns="http://www.w3.org/2000/svg"', 1)
        with open(os.path.join(image_dir, name), "w", encoding="utf-8") as out:
            out.write(svg)
        return f'<img src="{name}" alt="figure" />'

    html = _SVG_RE.sub(repl, html)
    with open(html_path, "w", encoding="utf-8") as f:
        f.write(html)
    return count[0]


def _strip_wrapper_tags(markdown):
    """Drop standalone structural-wrapper tag lines pandoc left behind.

    With ``-raw_html`` pandoc unwraps LaTeXML's ``ltx_*`` ``<div>``/``<span>``s
    but still emits the document's outermost ``<article>``/``<section>`` open
    and close tags as raw lines. They carry no content, so removing the
    tag-only lines leaves the prose untouched.
    """
    lines = [ln for ln in markdown.splitlines()
             if not _WRAPPER_TAG_RE.match(ln)]
    return "\n".join(lines)


def _collect_images(markdown):
    """List the image references in the Markdown, with section context.

    Returns one dict per ``![caption](path)`` in document order::

        {"path": ..., "caption": ..., "section": ["Header 1 text", ...]}

    ``section`` is the stack of Markdown headers in force at the image,
    outermost first -- the natural anchor for attaching a figure to the chunk
    it belongs to.
    """
    stack = {}
    images = []
    for line in markdown.splitlines():
        h = _HEADER_RE.match(line)
        if h:
            level = len(h.group(1))
            stack[level] = h.group(2).strip()
            for deeper in [lvl for lvl in stack if lvl > level]:
                del stack[deeper]
            continue
        for m in _MD_IMG_RE.finditer(line):
            images.append({
                "path": m.group("path"),
                "caption": m.group("caption"),
                "section": [stack[lvl] for lvl in sorted(stack)],
            })
    return images


def latex_to_markdown(tex_path, image_dir=None, keep_html=False,
                      return_images=False, log_dir=None):
    """Convert a LaTeX file to Markdown (with images) using LaTeXML.

    LaTeXML has no direct Markdown writer, so the conversion runs in three
    stages: ``latexml`` turns the .tex into LaTeXML's XML, ``latexmlpost``
    renders that XML to HTML5 while converting/copying every figure (eps/pdf
    -> png/svg) into ``image_dir``, and ``pandoc`` finally turns the HTML into
    GitHub-flavored Markdown, keeping the ``<img>`` tags as ``![](path)``.

    To keep the Markdown clean for embedding/display, the HTML conversion
    drops LaTeXML's structural markup (the ``ltx_*`` ``<div>``/``<span>``
    wrappers) rather than passing it through as raw HTML. Figures still
    survive because every one is turned into a file reference first: PNGs by
    latexmlpost, and any inline ``<svg>`` by :func:`_clean_html`.

    Image links in the returned Markdown are relative to ``image_dir``.

    Args:
        tex_path: path to the input .tex file.
        image_dir: directory for the extracted images (and the intermediate
            files). Defaults to "<tex_basename>_files" beside the .tex file.
        keep_html: leave the intermediate .xml/.html in image_dir if True.
        return_images: if True, return ``(markdown, images)`` where ``images``
            is the list from :func:`_collect_images` -- each figure's path,
            caption and enclosing section headers, for attaching to chunks.
        log_dir: directory for the per-stage subprocess logs, written as
            "<base>.<tool>.log" (one each for latexml/latexmlpost/pandoc).
            Defaults to a "logs" folder inside ``image_dir``; pass a shared
            path to collect every conversion's logs in one place.

    Returns:
        The Markdown as a string, or ``(markdown, images)`` when
        ``return_images`` is True.
    """
    for tool in ("latexml", "latexmlpost", "pandoc"):
        if shutil.which(tool) is None:
            raise RuntimeError(
                f"{tool!r} not found on PATH. Install LaTeXML "
                "(`brew install latexml` or `cpan LaTeXML`) and pandoc."
            )

    tex_path = os.path.abspath(tex_path)
    if not os.path.isfile(tex_path):
        raise FileNotFoundError(tex_path)

    base = os.path.splitext(os.path.basename(tex_path))[0]
    if image_dir is None:
        image_dir = os.path.join(os.path.dirname(tex_path), base + "_files")
    os.makedirs(image_dir, exist_ok=True)

    # Logs live inside image_dir so they travel with the per-paper output
    # (which sits in the data dir) and never land in the working directory.
    if log_dir is None:
        log_dir = os.path.join(image_dir, "logs")
    os.makedirs(log_dir, exist_ok=True)

    xml_path = os.path.join(image_dir, base + ".xml")
    html_path = os.path.join(image_dir, base + ".html")

    # External \includegraphics figures (PDF/EPS) are rasterized to PNG by
    # latexmlpost's graphicimages stage via Ghostscript. Without `gs` they
    # stay as <embed src="fig.pdf">, which pandoc can't turn into a Markdown
    # image and which doesn't render inline -- warn up front.
    if shutil.which("gs") is None:
        with open(tex_path, encoding="utf-8", errors="ignore") as f:
            if "\\includegraphics" in f.read():
                warnings.warn(
                    "Ghostscript ('gs') not found: external \\includegraphics "
                    "figures (PDF/EPS) won't convert to Markdown images. "
                    "Install with `brew install ghostscript`.",
                    stacklevel=2,
                )

    def run(cmd, expect=None):
        """Run cmd and return the completed process.

        When ``expect`` is given (the LaTeXML stages), success is defined by
        the output file existing -- not by the exit code. latexmlpost reports
        recoverable problems (e.g. a figure it can't rasterize without
        PerlMagick) as "errors" and may exit non-zero, yet still writes
        perfectly usable HTML; aborting on those would throw away a good
        conversion. So we only raise when the file is genuinely missing, and
        merely warn when it exists despite reported errors.

        When ``expect`` is None (pandoc) a non-zero exit is a hard failure.
        """
        proc = subprocess.run(cmd, capture_output=True, text=True,
                              env=_latexml_env())
        log = (proc.stdout + proc.stderr).strip()
        # The LaTeXML stages write their own log into log_dir via --log (set
        # on the commands below) -- otherwise they'd litter the working dir.
        # pandoc has no --log and its stdout is the Markdown payload, so we
        # persist its stderr diagnostics here instead.
        if expect is None:
            log_path = os.path.join(log_dir, f"{base}.{os.path.basename(cmd[0])}.log")
            with open(log_path, "w", encoding="utf-8") as lf:
                lf.write(f"$ {' '.join(cmd)}\n(exit {proc.returncode})\n\n"
                         f"{proc.stderr.strip()}\n")
        if expect is not None:
            if os.path.exists(expect):
                if proc.returncode != 0 or "Error:" in log:
                    warnings.warn(
                        f"{cmd[0]} reported problems but produced {expect}; "
                        f"continuing.\n{log}",
                        stacklevel=2,
                    )
                return proc
            listing = ", ".join(sorted(os.listdir(os.path.dirname(expect)
                                                   or "."))) or "(empty)"
            raise RuntimeError(
                f"{cmd[0]} exited {proc.returncode} and wrote no {expect}.\n"
                f"Directory holds: {listing}\n{log}"
            )
        if proc.returncode != 0:
            raise RuntimeError(f"{cmd[0]} exited {proc.returncode}:\n{log}")
        return proc

    # .tex -> LaTeXML XML. --log keeps LaTeXML's log in log_dir; without it
    # the tool writes "<base>.latexml.log" into the working directory.
    run(["latexml", "--log=" + os.path.join(log_dir, base + ".latexml.log"),
         "--dest", xml_path, tex_path], expect=xml_path)
    # XML -> HTML5, extracting/converting figures into image_dir. With
    # Image::Magick available (see _latexml_env), latexmlpost rasterizes
    # EPS/PDF and picture/TikZ graphics to PNG; html5 still renders simple
    # pictures as inline SVG where it can. --log, as above, keeps its log out
    # of the working directory.
    run(["latexmlpost",
         "--log=" + os.path.join(log_dir, base + ".latexmlpost.log"),
         "--format=html5", "--dest", html_path, xml_path], expect=html_path)
    # Drop the LaTeXML page footer and turn any inline <svg> into a standalone
    # .svg file + <img> reference, so every figure is a file reference before
    # pandoc runs.
    _clean_html(html_path, image_dir, base)
    # HTML -> Markdown (GFM). <img> figures become ![](...). -raw_html drops
    # the HTML pandoc can't express as Markdown -- chiefly LaTeXML's ltx_*
    # wrapper <div>/<span>s -- so the output is clean text plus image refs.
    # (Graphics aren't lost: they're all <img> files by this point.)
    proc = run(["pandoc", "--from=html+raw_html", "--to=gfm-raw_html",
                "--wrap=none", html_path])
    markdown = _strip_wrapper_tags(proc.stdout)

    if not keep_html:
        for path in (xml_path, html_path):
            if os.path.exists(path):
                os.remove(path)

    if return_images:
        return markdown, _collect_images(markdown)
    return markdown


if __name__ == "__main__":
    import sys

    print(latex_to_markdown(sys.argv[1]))
